-- migration_zzzzzzzz_pocket_money_server_only.sql — only the server writes
-- pocket-money data.
--
-- The browser roles held INSERT, UPDATE and DELETE on every pocket_money_*
-- table from the Supabase image's blanket grant, under FOR ALL row-level
-- security policies scoped to the caller's family. So a family's own token —
-- any screen in the household, a child's wall panel included — could write
-- straight through the database API:
--
--   UPDATE pocket_money_accounts SET balance_cents = 999999   -> UPDATE 1
--
-- and the same for best_tier, reward_mode, the allowance, interest, a booked
-- transaction or a withdrawal request's status. That walks past every rule the
-- server routes enforce, the settings PIN (#353, #359) first among them.
--
-- What the browser does with these tables:
--   SELECT  through PostgREST and realtime (the reads stay, untouched here)
--   writes  none. Every write is a /api/pocket-money/* route, or the booking
--           functions, on the service role, which these revokes do not touch.
--           The PIN-free kid-side actions (goals, withdrawal requests, the
--           avatar-stage high-water mark) are routes too, PIN-free by design.
--
-- A loop over every table named pocket_money_* rather than a list, so a table
-- the plugin adds later is covered on the first boot after it exists.
--
-- RLS policies are left as they are. They are FOR ALL and generated by the
-- direct_tables loop in migration_zz_row_level_security.sql; with the write
-- privileges gone a write fails on permission before any policy is consulted,
-- and that holds whatever a policy says.
--
-- Sorted after every migration that creates or grants on a pocket_money_*
-- table (`zzzzzzzz`), and idempotent: REVOKE of a privilege that is not held is
-- a no-op, so this is safe on every boot.

DO $$
DECLARE
  t TEXT;
  role_name TEXT;
BEGIN
  FOR t IN
    SELECT c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind IN ('r', 'p')
      AND c.relname LIKE 'pocket\_money\_%'
    ORDER BY c.relname
  LOOP
    FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated'] LOOP
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
        EXECUTE format('REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON TABLE public.%I FROM %I', t, role_name);
      END IF;
    END LOOP;
  END LOOP;
END $$;
