/**
 * Attaches a correlation ID to every request.
 *
 * Phase 0 of the 2026 plan asks for correlation IDs. The problem they solve:
 * a household reports "it said something went wrong" and there is nothing
 * connecting that sentence to a line in `docker logs kinboard-webapp`. With
 * this, the ID shown in the error body is the ID in the log line.
 *
 * An inbound `x-correlation-id` is **honoured rather than replaced**, so an ID
 * generated by Home Assistant, the Bridge or a reverse proxy survives the hop
 * and one ID covers the whole chain. That is the property that makes this
 * worth having once RFC-001's Integration API exists.
 *
 * Deliberately minimal: no logging, no auth, no rewriting. Middleware runs on
 * every matched request including static assets, so anything expensive here is
 * paid on every page view of a wall display that never sleeps.
 */

import { NextResponse, type NextRequest } from "next/server";
import {
  CORRELATION_HEADER,
  newCorrelationId,
  sanitiseCorrelationId,
} from "@/lib/correlation";

export function middleware(request: NextRequest) {
  const id = sanitiseCorrelationId(request.headers.get(CORRELATION_HEADER)) ?? newCorrelationId();

  // Forward to the route handler, which reads it via headers().
  const forwarded = new Headers(request.headers);
  forwarded.set(CORRELATION_HEADER, id);

  const response = NextResponse.next({ request: { headers: forwarded } });
  // And back to the caller, so a client can log the ID without parsing a body
  // — including on responses that have no body at all.
  response.headers.set(CORRELATION_HEADER, id);
  return response;
}

export const config = {
  /**
   * API routes only. The IDs exist to correlate API failures with log lines;
   * running this on every image, font and prefetch would add work to the
   * hottest path in the app for no diagnostic gain.
   */
  matcher: "/api/:path*",
};
