#!/usr/bin/env node
//
// Renders stats/traffic.json into stats/README.md.
//
// The JSON is the record; this is the thing a human actually reads when
// they want to know whether anyone is using Kinboard. Kept as a separate
// script so the summary can be regenerated without re-hitting the API.

import { readFileSync, writeFileSync } from "node:fs";

const data = JSON.parse(readFileSync("stats/traffic.json", "utf8"));
const days = Object.entries(data.days).sort(([a], [b]) => a.localeCompare(b));

/** Sum a field over the last n tracked days. */
const sum = (field, n) =>
  days.slice(-n).reduce((acc, [, d]) => acc + (d[field] ?? 0), 0);

/**
 * Unique visitors can't be summed across days — the same person on two
 * days is one person twice, and adding them overstates reach. Report the
 * daily peak instead, which is a real number rather than a fake one.
 */
const peak = (field, n) =>
  days.slice(-n).reduce((acc, [, d]) => Math.max(acc, d[field] ?? 0), 0);

const latest = data.snapshots.at(-1) ?? {};
const first = data.snapshots[0] ?? {};
const growth = (field) => {
  const delta = (latest[field] ?? 0) - (first[field] ?? 0);
  return delta > 0 ? ` (+${delta})` : "";
};

const spark = (field, n = 30) => {
  const blocks = "▁▂▃▄▅▆▇█";
  const vals = days.slice(-n).map(([, d]) => d[field] ?? 0);
  const max = Math.max(...vals, 1);
  return vals.map((v) => blocks[Math.min(7, Math.floor((v / max) * 7))]).join("");
};

const md = `# Usage stats

<!-- Generated by scripts/render-stats.mjs — do not edit by hand. -->

Last updated: \`${data.updated}\` · tracking **${days.length}** days

## Right now

| | |
|---|---|
| Stars | ${latest.stars ?? "?"}${growth("stars")} |
| Forks | ${latest.forks ?? "?"}${growth("forks")} |
| Watchers | ${latest.watchers ?? "?"}${growth("watchers")} |
| Open issues | ${latest.open_issues ?? "?"} |

## Traffic

| | Last 7 days | Last 30 days |
|---|---|---|
| Clones | ${sum("clones", 7)} | ${sum("clones", 30)} |
| Unique cloners (peak day) | ${peak("clone_uniques", 7)} | ${peak("clone_uniques", 30)} |
| Views | ${sum("views", 7)} | ${sum("views", 30)} |
| Unique visitors (peak day) | ${peak("view_uniques", 7)} | ${peak("view_uniques", 30)} |

\`\`\`
clones  ${spark("clones")}
views   ${spark("views")}
\`\`\`

## What this does and doesn't measure

These are **GitHub's own numbers about github.com**, read back by the repo
owner once a day. Kinboard installs send nothing anywhere — there is no
telemetry in the product, and none is planned by default.

That means this answers *"is interest growing?"* and not *"how many
installs are running?"*. Nothing short of a phone-home can answer the
second, and for a self-hosted product that markets itself on privacy,
the trade isn't worth it. A clone is also not an install: CI, mirrors and
scrapers clone too.

Unique counts are reported as a **peak day** rather than a sum, because
the same person visiting on two days is one person, and adding the daily
figures would overstate reach.

The API only exposes the last 14 days and keeps no history, so this file
is the archive. A gap in the series means the workflow didn't run.
`;

writeFileSync("stats/README.md", md);
console.log(`rendered stats/README.md (${days.length} days)`);
