export const DEFAULT_MONTHLY_TERMS: Record<string, string[]> = {
  "1": [
    "winter landscape snow mountains",
    "frost architecture minimalist",
    "industrial plant winter fog",
    "northern lights aurora night",
    "frozen lake ice nature",
    "city night winter lights",
    "snowy forest path peaceful",
    "abandoned building snow urban",
  ],
  "2": [
    "frost nature macro closeup",
    "foggy forest mystical moody",
    "industrial harbor morning light",
    "snow covered bridge architecture",
    "ice crystals macro",
    "quiet winter street city",
    "mountain cabin snow cozy",
    "skyscraper fog moody dark",
  ],
  "3": [
    "spring blossoms buds closeup",
    "rainy city reflection night",
    "abandoned building urban decay",
    "spring forest morning mist",
    "old factory brickwork industrial",
    "crocus snowdrop early spring",
    "harbor cranes industrial port",
    "mountain stream spring meltwater",
  ],
  "4": [
    "cherry blossom spring flowers",
    "steel bridge architecture detail",
    "tulip field panorama colorful",
    "raindrops window city lights",
    "factory chimney dramatic clouds",
    "blooming orchard spring",
    "old railway tracks abandoned",
    "morning dew meadow macro",
  ],
  "5": [
    "wildflower meadow colorful",
    "lighthouse coast dramatic waves",
    "abandoned train station tracks",
    "rapeseed field yellow panorama",
    "mountain road alps serpentine",
    "city park green spring",
    "wind turbine landscape sunset",
    "waterfall forest long exposure",
  ],
  "6": [
    "summer golden hour sunset",
    "industrial zone sunset silhouette",
    "lavender field provence summer",
    "city skyline evening sky",
    "poppy cornfield red summer",
    "sailboat lake summer peaceful",
    "steel mill sparks night",
    "alpine meadow panorama flowers",
  ],
  "7": [
    "beach ocean sunset dramatic",
    "container port cranes industrial",
    "milky way starry night nature",
    "summer storm dramatic clouds",
    "old town alley mediterranean",
    "golden wheat field harvest",
    "neon city night urban",
    "mountain lake turquoise alpine",
  ],
  "8": [
    "sunflower field summer golden",
    "power plant cooling towers steam",
    "hot air balloon landscape dawn",
    "wheat field sunset golden hour",
    "abandoned pool urban exploration",
    "summer night stars long exposure",
    "vineyard hills tuscany landscape",
    "rusty ship harbor decay",
  ],
  "9": [
    "early autumn golden light forest",
    "dam hydropower concrete massive",
    "morning fog river landscape",
    "mushrooms forest floor closeup",
    "old mill autumn countryside",
    "grape harvest vineyard autumn",
    "factory ruin nature overgrown",
    "sunrise fog fields pastoral",
  ],
  "10": [
    "autumn foliage forest colorful",
    "industrial wasteland urban exploration",
    "foggy tree lined avenue autumn",
    "pumpkin field harvest october",
    "rusty bridge river decay",
    "colorful autumn forest panorama",
    "abandoned hall graffiti urban",
    "spider web dew morning macro",
  ],
  "11": [
    "foggy autumn forest mystical dark",
    "smokestack industrial chimney",
    "bare trees silhouette sunset moody",
    "rainy city lights night reflection",
    "old warehouse brick industrial",
    "stormy sea waves coast dramatic",
    "street lanterns fog old town",
    "steam locomotive fog nostalgic",
  ],
  "12": [
    "christmas market lights night cozy",
    "snow covered factory industrial winter",
    "candles christmas warm atmosphere",
    "winter city snow night street",
    "nordic landscape snow fjord",
    "starry sky winter clear cold",
    "icicles architecture detail frost",
    "fireplace cozy warm winter cabin",
  ],
};

export const MONTH_NAMES = [
  "Januar", "Februar", "März", "April", "Mai", "Juni",
  "Juli", "August", "September", "Oktober", "November", "Dezember",
];
