export const DEFAULT_MONTHLY_TERMS: Record<string, string[]> = {
  "1": [
    "winter landscape snow mountains",
    "frost architecture minimalist",
    "industrial plant winter fog",
    "northern lights aurora night",
    "frozen lake ice nature",
    "city night winter lights",
    "snowy forest path peaceful",
    "abandoned building snow urban",
    "winter sunrise pastel sky",
    "cosy window frost indoors",
    "pine trees heavy snow",
    "empty beach winter grey",
    "mountain range clear cold day",
    "warm lamplight snowy evening",
  ],
  "2": [
    "frost nature macro closeup",
    "foggy forest mystical moody",
    "industrial harbor morning light",
    "snow covered bridge architecture",
    "ice crystals macro",
    "quiet winter street city",
    "mountain cabin snow cozy",
    "skyscraper fog moody dark",
    "late winter bare trees",
    "harbour ice morning",
    "snowdrops first green shoots",
    "low sun long shadows winter",
    "stone bridge frozen river",
    "carnival colours street",
  ],
  "3": [
    "spring blossoms buds closeup",
    "rainy city reflection night",
    "abandoned building urban decay",
    "spring forest morning mist",
    "old factory brickwork industrial",
    "crocus snowdrop early spring",
    "harbor cranes industrial port",
    "mountain stream spring meltwater",
    "spring rain fresh green",
    "budding branches close up",
    "windswept coast spring",
    "daffodils bright yellow",
    "clearing sky after storm",
    "garden waking up spring",
  ],
  "4": [
    "cherry blossom spring flowers",
    "steel bridge architecture detail",
    "tulip field panorama colorful",
    "raindrops window city lights",
    "factory chimney dramatic clouds",
    "blooming orchard spring",
    "old railway tracks abandoned",
    "morning dew meadow macro",
    "fresh leaves backlit green",
    "spring meadow wide open",
    "rain puddle reflections street",
    "magnolia blossom pink",
    "country lane spring hedgerow",
    "bright overcast soft light",
  ],
  "5": [
    "wildflower meadow colorful",
    "lighthouse coast dramatic waves",
    "abandoned train station tracks",
    "rapeseed field yellow panorama",
    "mountain road alps serpentine",
    "city park green spring",
    "wind turbine landscape sunset",
    "waterfall forest long exposure",
    "lush green hillside",
    "lilac and wisteria bloom",
    "early summer riverbank",
    "open window breeze curtains",
    "green canopy path walking",
    "clouds over green fields",
  ],
  "6": [
    "summer golden hour sunset",
    "industrial zone sunset silhouette",
    "lavender field provence summer",
    "city skyline evening sky",
    "poppy cornfield red summer",
    "sailboat lake summer peaceful",
    "steel mill sparks night",
    "alpine meadow panorama flowers",
    "long summer evening light",
    "wildflower verge roadside",
    "coastline blue sea summer",
    "picnic blanket grass",
    "garden in full bloom",
    "warm dusk silhouettes",
  ],
  "7": [
    "beach ocean sunset dramatic",
    "container port cranes industrial",
    "milky way starry night nature",
    "summer storm dramatic clouds",
    "old town alley mediterranean",
    "golden wheat field harvest",
    "neon city night urban",
    "mountain lake turquoise alpine",
    "high summer haze heat",
    "lavender field rows",
    "sea swimming clear water",
    "shade under big tree",
    "summer festival lights night",
    "dry grass golden hour",
  ],
  "8": [
    "sunflower field summer golden",
    "power plant cooling towers steam",
    "hot air balloon landscape dawn",
    "wheat field sunset golden hour",
    "abandoned pool urban exploration",
    "summer night stars long exposure",
    "vineyard hills tuscany landscape",
    "rusty ship harbor decay",
    "late summer harvest fields",
    "sunflower field summer",
    "warm stone village evening",
    "river swimming summer calm",
    "end of summer coastline",
    "dusty road summer heat",
  ],
  "9": [
    "early autumn golden light forest",
    "dam hydropower concrete massive",
    "morning fog river landscape",
    "mushrooms forest floor closeup",
    "old mill autumn countryside",
    "grape harvest vineyard autumn",
    "factory ruin nature overgrown",
    "sunrise fog fields pastoral",
    "early autumn first colour",
    "misty morning fields",
    "apple orchard harvest",
    "back to school autumn street",
    "heather moorland purple",
    "soft september light",
  ],
  "10": [
    "autumn foliage forest colorful",
    "industrial wasteland urban exploration",
    "foggy tree lined avenue autumn",
    "pumpkin field harvest october",
    "rusty bridge river decay",
    "colorful autumn forest panorama",
    "abandoned hall graffiti urban",
    "spider web dew morning macro",
    "autumn leaves deep colour",
    "foggy woodland path",
    "pumpkins market stall",
    "rain on window autumn",
    "golden birch forest",
    "stormy coast autumn",
  ],
  "11": [
    "foggy autumn forest mystical dark",
    "smokestack industrial chimney",
    "bare trees silhouette sunset moody",
    "rainy city lights night reflection",
    "old warehouse brick industrial",
    "stormy sea waves coast dramatic",
    "street lanterns fog old town",
    "steam locomotive fog nostalgic",
    "bare branches grey sky",
    "late autumn frost morning",
    "warm café window rainy",
    "misty river valley",
    "last leaves clinging",
    "low november sun trees",
  ],
  "12": [
    "christmas market lights night cozy",
    "snow covered factory industrial winter",
    "candles christmas warm atmosphere",
    "winter city snow night street",
    "nordic landscape snow fjord",
    "starry sky winter clear cold",
    "icicles architecture detail frost",
    "fireplace cozy warm winter cabin",
    "winter market lights evening",
    "candlelight warm interior",
    "snow falling street lamp",
    "frosted window pattern",
    "quiet snowy village",
    "long winter night sky stars",
  ],
};

export const MONTH_NAMES = [
  "Januar", "Februar", "März", "April", "Mai", "Juni",
  "Juli", "August", "September", "Oktober", "November", "Dezember",
];
